// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ElevatorAppData.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ElevatorAppData.Models
{
    public partial interface IElevatorSystemContextProcedures
    {
        Task<List<spElevatorRequestResult>> spElevatorRequestAsync(int? CurrentFloor, int? RequestedFloor, string BuildingName, string ElevatorName, int? DirectionCd, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetAvailableElevatorsResult>> spGetAvailableElevatorsAsync(int? CurrentFloor, string BuildingName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spUpdateElevatorStateResult>> spUpdateElevatorStateAsync(string ElevatorName, int? DirectionCd, int? CurrentFloor, string Status, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
