// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ElevatorAppData.Models
{
    public partial class spUpdateElevatorStateResult
    {
        public int RequestId { get; set; }
        public int? ElevatorId { get; set; }
        public int BuildingId { get; set; }
        public int DirectionId { get; set; }
        public int RequestedFromFloorId { get; set; }
        public int CurrentFloorId { get; set; }
        public int RequestedToFloorId { get; set; }
        public DateTime RequestTime { get; set; }
        public string Status { get; set; }
    }
}
